import { Router } from "express";

export default function initRoute(router: Router): void {
  router.get("/api/v1/events/Fortnite/download/:user", (req, res) => {
    res.status(204).json({
      player: {
        gameId: "Fortnite",
        accountId: req.params.user,
        tokens: [
          "ARENA_Division2",
          "ARENA_Division3",
          "ARENA_S11_Division1",
          "ARENA_S11_Division2",
          "ARENA_S11_Division3",
          "ARENA_S12_Division1",
          "ARENA_S12_Division2",
          "ARENA_S12_Division3",
          "ARENA_S13_Division1",
          "ARENA_S13_Division2",
          "ARENA_S14_Division1",
          "ARENA_S14_Division2",
          "ARENA_S14_Division3",
          "ARENA_S14_Division4",
          "ARENA_S15_Division1",
          "ARENA_S15_Division2",
          "ARENA_S15_Division3",
          "ARENA_S15_Division4",
          "ARENA_S15_Division5",
          "ARENA_S16_Division1",
          "ARENA_S16_Division2",
          "ARENA_S16_Division3",
          "ARENA_S16_Division4",
          "ARENA_S17_Division1",
          "ARENA_S17_Division2",
          "ARENA_S17_Division3",
          "ARENA_S17_Division4",
          "ARENA_S17_Division5",
          "ARENA_S17_Division6",
          "ARENA_S19_Division1",
          "ARENA_S20_Division1",
          "ARENA_S21v2_Division1",
          "Arena_S22_Division1",
          "BLUECHEESEARENA_S17_Division1",
          "BLUECHEESEARENA_S17_Division2",
          "BLUECHEESEARENA_S17_Division3",
          "BLUECHEESEARENA_S18_Division1",
          "BLUECHEESEARENA_S18_Division2",
          "BLUECHEESEARENA_S18_Division3",
          "BLUECHEESEARENA_S18_Division4",
          "BoxFightArenaTest_S16_Division1",
          "GroupIdentity_GeoIdentity_global",
          "LGArena_S21_v2_Division1",
          "LGArena_S21_v2_Division2",
          "RegionLock_S14_MarvelSuperCup_NAE",
          "RegionLock_S15_FrostyFrenzy_NAE",
          "RegionLock_S16_NeymarJrCup_NAE",
          "Season23thekidlaroi_NAE",
        ],
        teams: {},
        pendingPayouts: [],
        pendingPenalties: {},
        persistentScores: {
          Hype_S22_P: 90,
          LGHype_S21_Pv2: 451,
          Hype_S19_P: 75,
          Hype_S15: 1526,
          Hype_S10: 302,
          Hype: 122,
          Hype_S14: 1132,
          Bluecheese_Hype_S18_P: 908,
          BoxFightTestHype_S16: 140,
          Hype_S12: 628,
          Hype_S17: 2595,
          Hype_S16: 1142,
          Hype_S11: 1320,
          Hype_S21_Pv2: 210,
          Bluecheese_Hype_S17: 377,
          Hype_S20_P: 0,
          Hype_S13: 333,
        },
        groupIdentity: {
          GeoIdentity: "global",
        },
      },
      events: [
        {
          gameId: "Fortnite",
          eventId: "epicgames_S23_ZBMQuickCupFill_EU",
          regions: ["EU"],
          regionMappings: {},
          platforms: [
            "XboxOneGDK",
            "PS4",
            "XCloud",
            "Helios",
            "XCloudMobile",
            "XboxOne",
            "XSX",
            "Android",
            "PS5",
            "HeliosMobile",
            "GFN",
            "Switch",
            "GFNMobile",
            "Windows",
          ],
          platformMappings: {},
          displayDataId: "s23_zbm_duosquick_fill",
          eventGroup: "Season23ZBMQuickCupFill",
          announcementTime: "2022-05-21T14:00:00.000Z",
          appId: null,
          environment: null,
          link: {
            type: "br:tournament",
            code: "tournament_epicgames_s23_zbmquickcupfill_eu",
            version: 1,
          },
          metadata: {
            TeamLockType: "Window",
            minimumAccountLevel: 15,
            DisqualifyType: "Event",
            RegionLockType: "Event",
            AccountLockType: "Window",
          },
          eventWindows: [
            {
              eventWindowId: "S23_ZBMQuickCupFill_Event1_EU",
              eventTemplateId: "EventTemplate_S23_ZBMQuickCupFill_EU",
              countdownBeginTime: "2022-12-14T17:30:00.000Z",
              beginTime: "2022-12-14T18:00:00.000Z",
              endTime: "2022-12-14T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_EU",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: [
                "Season23ZBMQuickCupFill_ME",
                "Season23ZBMQuickCupFill_ASIA",
                "Season23ZBMQuickCupFill_OCE",
                "Season23ZBMQuickCupFill_NAW",
                "Season23ZBMQuickCupFill_BR",
                "Season23ZBMQuickCupFill_NAE",
              ],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S23_ZBMQuickCupFill_Event2_EU",
              eventTemplateId: "EventTemplate_S23_ZBMQuickCupFill_EU",
              countdownBeginTime: "2023-01-04T17:30:00.000Z",
              beginTime: "2023-01-04T18:00:00.000Z",
              endTime: "2023-01-04T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_EU",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: [
                "Season23ZBMQuickCupFill_ME",
                "Season23ZBMQuickCupFill_ASIA",
                "Season23ZBMQuickCupFill_OCE",
                "Season23ZBMQuickCupFill_NAW",
                "Season23ZBMQuickCupFill_BR",
                "Season23ZBMQuickCupFill_NAE",
              ],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S23_ZBMQuickCupFill_Event3_EU",
              eventTemplateId: "EventTemplate_S23_ZBMQuickCupFill_EU",
              countdownBeginTime: "2023-01-11T17:30:00.000Z",
              beginTime: "2023-01-11T18:00:00.000Z",
              endTime: "2023-01-11T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_EU",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: [
                "Season23ZBMQuickCupFill_ME",
                "Season23ZBMQuickCupFill_ASIA",
                "Season23ZBMQuickCupFill_OCE",
                "Season23ZBMQuickCupFill_NAW",
                "Season23ZBMQuickCupFill_BR",
                "Season23ZBMQuickCupFill_NAE",
              ],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S23_ZBMQuickCupFill_Event4_EU",
              eventTemplateId: "EventTemplate_S23_ZBMQuickCupFill_EU",
              countdownBeginTime: "2023-01-18T17:30:00.000Z",
              beginTime: "2023-01-18T18:00:00.000Z",
              endTime: "2023-01-18T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_EU",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: [
                "Season23ZBMQuickCupFill_ME",
                "Season23ZBMQuickCupFill_ASIA",
                "Season23ZBMQuickCupFill_OCE",
                "Season23ZBMQuickCupFill_NAW",
                "Season23ZBMQuickCupFill_BR",
                "Season23ZBMQuickCupFill_NAE",
              ],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S23_ZBMQuickCupFill_Event5_EU",
              eventTemplateId: "EventTemplate_S23_ZBMQuickCupFill_EU",
              countdownBeginTime: "2023-01-25T17:30:00.000Z",
              beginTime: "2023-01-25T18:00:00.000Z",
              endTime: "2023-01-25T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_EU",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: [
                "Season23ZBMQuickCupFill_ME",
                "Season23ZBMQuickCupFill_ASIA",
                "Season23ZBMQuickCupFill_OCE",
                "Season23ZBMQuickCupFill_NAW",
                "Season23ZBMQuickCupFill_BR",
                "Season23ZBMQuickCupFill_NAE",
              ],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S23_ZBMQuickCupFill_Event6_EU",
              eventTemplateId: "EventTemplate_S23_ZBMQuickCupFill_v2_EU",
              countdownBeginTime: "2023-02-01T17:30:00.000Z",
              beginTime: "2023-02-01T18:00:00.000Z",
              endTime: "2023-02-01T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_EU",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: [
                "Season23ZBMQuickCupFill_ME",
                "Season23ZBMQuickCupFill_ASIA",
                "Season23ZBMQuickCupFill_OCE",
                "Season23ZBMQuickCupFill_NAW",
                "Season23ZBMQuickCupFill_BR",
                "Season23ZBMQuickCupFill_NAE",
              ],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S23_ZBMQuickCupFill_Event7_EU",
              eventTemplateId: "EventTemplate_S23_ZBMQuickCupFill_v2_EU",
              countdownBeginTime: "2023-02-08T17:30:00.000Z",
              beginTime: "2023-02-08T18:00:00.000Z",
              endTime: "2023-02-08T21:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_EU",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: [
                "Season23ZBMQuickCupFill_ME",
                "Season23ZBMQuickCupFill_ASIA",
                "Season23ZBMQuickCupFill_OCE",
                "Season23ZBMQuickCupFill_NAW",
                "Season23ZBMQuickCupFill_BR",
                "Season23ZBMQuickCupFill_NAE",
              ],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S23_ZBMQuickCupFill_Event8_EU",
              eventTemplateId: "EventTemplate_S23_ZBMQuickCupFill_v2_EU",
              countdownBeginTime: "2023-02-15T17:30:00.000Z",
              beginTime: "2023-02-15T18:00:00.000Z",
              endTime: "2023-02-15T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_NAE",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: ["Season12EonDuoVbucksCup_NAE"],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S12_EonDuoVbucksCup_Event9_NAE",
              eventTemplateId: "EventTemplate_S12_EonDuoVbucksCup_v2_NAE",
              countdownBeginTime: "2023-02-22T17:30:00.000Z",
              beginTime: "2023-02-22T18:00:00.000Z",
              endTime: "2023-02-22T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_NAE",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: ["Season12EonDuoVbucksCup_NAE"],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s12_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
            {
              eventWindowId: "S12_EonDuoVbucksCup_Event10_NAE",
              eventTemplateId: "EventTemplate_S12_EonDuoVbucksCup_v2_NAE",
              countdownBeginTime: "2023-03-01T17:30:00.000Z",
              beginTime: "2023-03-01T18:00:00.000Z",
              endTime: "2023-03-01T20:00:00.000Z",
              blackoutPeriods: [],
              round: 0,
              payoutDelay: 30,
              isTBD: false,
              canLiveSpectate: false,
              scoreLocations: [
                {
                  scoreMode: "window",
                  scoreId: null,
                  leaderboardId: "Fortnite_EU",
                  useIndividualScores: true,
                  windowEndCondition: null,
                },
              ],
              visibility: "public",
              requireAllTokens: [],
              requireAnyTokens: [],
              requireNoneTokensCaller: ["Season12_EonDuoVbucksCup_NAE"],
              requireAllTokensCaller: [],
              requireAnyTokensCaller: [],
              additionalRequirements: ["mfa", "eula:s23_zbm_rules"],
              teammateEligibility: "all",
              regionMappings: null,
              metadata: {
                ServerReplays: true,
                RoundType: "Qualifiers",
              },
            },
          ],
          beginTime: "2022-12-14T18:00:00.000Z",
          endTime: "2023-03-01T20:00:00.000Z",
        },
      ],
      templates: [
        {
          gameId: "Fortnite",
          eventTemplateId: "EventTemplate_S12_EonDuoVbucks_NA",
          playlistId: "Playlist_ShowdownTournament_NoBuildBR_Duos",
          matchCap: 6,
          liveSessionAttributes: [],
          scoringRules: [
            {
              trackedStat: "PLACEMENT_STAT_INDEX",
              matchRule: "lte",
              rewardTiers: [
                {
                  keyValue: 1,
                  pointsEarned: 9,
                  multiplicative: false,
                },
                {
                  keyValue: 2,
                  pointsEarned: 4,
                  multiplicative: false,
                },
                {
                  keyValue: 3,
                  pointsEarned: 4,
                  multiplicative: false,
                },
                {
                  keyValue: 4,
                  pointsEarned: 4,
                  multiplicative: false,
                },
                {
                  keyValue: 5,
                  pointsEarned: 4,
                  multiplicative: false,
                },
                {
                  keyValue: 6,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 7,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 8,
                  pointsEarned: 1,
                  multiplicative: false,
                },
                {
                  keyValue: 9,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 10,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 11,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 12,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 13,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 14,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 15,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 16,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 17,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 18,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 19,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 20,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 21,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 22,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 23,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 24,
                  pointsEarned: 2,
                  multiplicative: false,
                },
                {
                  keyValue: 25,
                  pointsEarned: 2,
                  multiplicative: false,
                },
              ],
            },
            {
              trackedStat: "TEAM_ELIMS_STAT_INDEX",
              matchRule: "gte",
              rewardTiers: [
                {
                  keyValue: 1,
                  pointsEarned: 2,
                  multiplicative: true,
                },
              ],
            },
          ],
          tiebreakerFormula: {
            basePointsBits: 11,
            components: [
              {
                trackedStat: "VICTORY_ROYALE_STAT",
                bits: 4,
                multiplier: null,
                aggregation: "sum",
              },
              {
                trackedStat: "TEAM_ELIMS_STAT_INDEX",
                bits: 12,
                multiplier: 100,
                aggregation: "avg",
              },
              {
                trackedStat: "PLACEMENT_TIEBREAKER_STAT",
                bits: 14,
                multiplier: 100,
                aggregation: "avg",
              },
              {
                trackedStat: "TIME_ALIVE_STAT",
                bits: 11,
                multiplier: null,
                aggregation: "avg",
              },
            ],
          },
          payoutTable: [
            {
              scoreId: null,
              scoringType: "value",
              ranks: [
                {
                  threshold: 0,
                  payouts: [
                    {
                      rewardType: "token",
                      rewardMode: "rolling",
                      value: "Season23ZBMQuickCup_EU",
                      quantity: 1,
                    },
                  ],
                },
              ],
            },
          ],
          onlyScoreTopN: null,
          clampsToZero: false,
        },
      ],
      leaderboardDefs: [],
      scoringRuleSets: {},
      payoutTables: {},
      scores: [],
      resolvedWindowLocations: {
        "Fortnite:epicgames_S12_EonDuoVbucks_NA:S12_EonDuoVbucks_Event6_EU": [
          "Fortnite:epicgames_S12_EonDuoVbucks_NA:S12_EonDuoVbucks_NA",
        ],
      },
    });
  });
}
